/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_swim_HelloWorld */

#ifndef _Included_ai_swim_HelloWorld
#define _Included_ai_swim_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_swim_HelloWorld
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_swim_HelloWorld_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
