/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_swim_ObjTest */

#ifndef _Included_ai_swim_ObjTest
#define _Included_ai_swim_ObjTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_swim_ObjTest
 * Method:    createObj
 * Signature: ()Lai/swim/ObjTest;
 */
JNIEXPORT jobject JNICALL Java_ai_swim_ObjTest_createObj
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
