/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_swim_RustByteReader */

#ifndef _Included_ai_swim_RustByteReader
#define _Included_ai_swim_RustByteReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_swim_RustByteReader
 * Method:    readAll
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ai_swim_RustByteReader_readAll
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
