[package]
name = "ffiproto"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.19.0"
bytes = "1.0"
tokio = { version = "1.1.1", features = ["rt-multi-thread", "macros", "io-util"] }
parking_lot = "0.11.0"